spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


eureka:
    client:
      service-url:
        defaultZone: http://localhost:9093/eureka/  # Point to the correct Eureka server URL
      register-with-eureka: true
      fetch-registry: true


server:
  port: 9090
