
server:
  port: 9092
spring:
  application:
    name: video-service

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/videodb?authSource=admin


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka/  # Point to the correct Eureka server URL
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
